services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aieduplatform-db
    environment:
      POSTGRES_DB: AIEduPlatformDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ziad#2251
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
